# Use an official Maven image as the build environment
FROM maven:3.8.5-openjdk-17-slim AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the wrapper files to the container
COPY .mvn/wrapper /app/.mvn/wrapper
COPY mvnw mvnw.cmd pom.xml /app/

# Copy the project files and directories to the container
COPY src /app/src/

# Build the project using Maven
RUN mvn clean package

# Use an official OpenJDK 17 image as the base image for running the application
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by Maven from the build environment to the runtime environment
COPY --from=builder /app/target/actuator-demo-0.0.1-SNAPSHOT.jar /app/

# Define the command to run your Java application
CMD ["java", "-jar", "actuator-demo-0.0.1-SNAPSHOT.jar"]

